# -*- coding: utf-8 -*-
"""Automated_Answer_Scoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n18jRJZMPS7xJoQQLLvGf9yDU7cnwkxN

Machine Learning:- Automated Answer Scoring

Step 1:- Checking the data
"""

import numpy as np
import pandas as pd

from google.colab import files
files.upload()

df = pd.read_csv('mohler_cleaned.csv', encoding='latin1')
df.head()

df.shape

"""Data Cleaning"""

df.info()

df.describe()

df.drop(['Question','source','ID'], axis=1, inplace=True)
df.head()

df.duplicated().sum()

df.shape

"""Step 2:-EDA (Exploratory Data Analysis)
This is a critical process that helps in data understanding, pattern discovery and outlier detection
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.histplot(df['Grade'])
plt.title("Distribution of Grades")
plt.xlabel("Grade")
plt.ylabel("Frequency")
plt.show()

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('all')

df['doctor_answer_length'] = df['Doctor_Answer'].apply(lambda x:len(nltk.word_tokenize(x)))
df.head()

sns.histplot(df['doctor_answer_length'])

df['student_answer_length'] = df['Student_Answer'].apply(lambda x:len(nltk.word_tokenize(x)))
df.head()

sns.histplot(df['student_answer_length'])

plt.figure(figsize=(8, 5))
sns.histplot(df['doctor_answer_length'], label="Doctor Answer")
sns.histplot(df['student_answer_length'], color='red',label="Student Answer")
plt.xlabel("Number of Words")
plt.ylabel("Count")
plt.title("Comparison of Answer Lengths (Doctor vs. Student)")
plt.legend()
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True)

plt.figure(figsize=(8,5))
sns.boxplot(data=df[['doctor_answer_length', 'student_answer_length', 'Grade']])
plt.title("Outliers Detection using Boxplot")
plt.show()

sns.boxplot(df['student_answer_length'])  # response_length = number of words in an answer
plt.show()

"""Step 3:-Data Preprocessing"""

df.dropna(inplace=True)

import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')

ps = PorterStemmer()

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    words = nltk.word_tokenize(text)

    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word.isalnum() and word not in stop_words]

    words = [ps.stem(word) for word in words]

    return " ".join(words)

df['Doctor_Answer'] = df['Doctor_Answer'].apply(clean_text)
df['Student_Answer'] = df['Student_Answer'].apply(clean_text)
df.head()

Q1 = df['Grade'].quantile(0.25)
Q3 = df['Grade'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Removing outliers (if any)
df = df[(df['Grade'] >= lower_bound) & (df['Grade'] <= upper_bound)]

class_counts = df['Grade'].value_counts()

# Resampling the minority class if there's a strong imbalance
min_class_size = class_counts.min()
balanced_df = df.groupby('Grade', group_keys=False).apply(lambda x: x.sample(min_class_size, replace=True))

# Shuffling the dataset
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Display processed data info
balanced_df.info(), balanced_df.head()

df.head()

df['Doctor_Word_Length'] = df['Doctor_Answer'].astype(str).apply(lambda x: len(x.split()))
df['Student_Word_Length'] = df['Student_Answer'].astype(str).apply(lambda x: len(x.split()))

# Set up subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. Grade Distribution
sns.histplot(balanced_df['Grade'], bins=10, kde=True, ax=axes[0], color="blue")
axes[0].set_title("Grade Distribution")
axes[0].set_xlabel("Grade")
axes[0].set_ylabel("Count")

# 2. Word Length Comparison (Doctor vs Student)
sns.kdeplot(df['Doctor_Word_Length'], label="Doctor Answer", ax=axes[1], color="red", fill=True)
sns.kdeplot(df['Student_Word_Length'], label="Student Answer", ax=axes[1], color="green", fill=True)
axes[1].set_title("Word Length Comparison")
axes[1].set_xlabel("Word Length")
axes[1].legend()

# 3. Box Plot for Grades (Outlier Detection)
sns.boxplot(y=balanced_df['Grade'], ax=axes[2], color="purple")
axes[2].set_title("Box Plot of Grades")
axes[2].set_ylabel("Grade")

# Show plots
plt.tight_layout()
plt.show()

from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
# Combine all text columns into a single column for vectorization
df["Combined_Text"] =  df["Doctor_Answer"] + " " + df["Student_Answer"]

# Initialize TF-IDF Vectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df["Combined_Text"])

# Convert the sparse matrix to a dense array
tfidf_array = tfidf_matrix.toarray()

# Print shape of transformed data
print("TF-IDF Feature Matrix Shape:", tfidf_array.shape)

df.head()

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(df["Combined_Text"])

# Convert to array
bow_array = bow_matrix.toarray()

print("Bag of Words Feature Matrix Shape:", bow_array.shape)

import pandas as pd
from sklearn.model_selection import train_test_split

# تحميل البيانات
df = pd.read_csv('mohler_cleaned.csv', encoding='latin-1')

# حذف الأعمدة الغير مهمة
df.drop(['Question', 'source', 'ID'], axis=1, inplace=True)

# حذف القيم الفارغة
df.dropna(inplace=True)

# تنظيف الدرجات وتحويلها لأعداد صحيحة (0 - 10)
df['Grade'] = df['Grade'].astype(int)

# تقليل الـ imbalance إن وجد
class_counts = df['Grade'].value_counts()
min_class_size = class_counts.min()
df = df.groupby('Grade', group_keys=False).apply(lambda x: x.sample(min_class_size, replace=True)).reset_index(drop=True)

# تقسيم البيانات
train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer

class TextSimilarityDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_length=128):
        self.data = dataframe
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sentence1 = self.data.iloc[idx]['Doctor_Answer']
        sentence2 = self.data.iloc[idx]['Student_Answer']
        label = self.data.iloc[idx]['Grade']

        encoding = self.tokenizer(sentence1, sentence2,
                                  truncation=True,
                                  padding='max_length',
                                  max_length=self.max_length,
                                  return_tensors='pt')

        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

# تحميل Tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# إعداد البيانات
train_dataset = TextSimilarityDataset(train_df, tokenizer)
val_dataset = TextSimilarityDataset(val_df, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

from transformers import AutoModelForSequenceClassification
from torch.optim import AdamW
from tqdm import tqdm

# تحميل النموذج مع عدد الفئات = 11 (0-10 درجات)
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=11)

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# GPU or CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Training loop
for epoch in range(3):  # عدد الـ epochs
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader):
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1} | Loss: {total_loss / len(train_loader):.4f}")

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from scipy.sparse import hstack


df['Grade_Scaled'] = df['Grade'] * 9 + 1  # 0 → 1, 1 → 10

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words='english')
vectorizer.fit(pd.concat([df['Doctor_Answer'], df['Student_Answer']]))

doctor_vecs = vectorizer.transform(df['Doctor_Answer'])
student_vecs = vectorizer.transform(df['Student_Answer'])

# Combine features
X = hstack([doctor_vecs, student_vecs])
y = df['Grade_Scaled']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict on all data
predictions_scaled = model.predict(X)
predictions_scaled = [round(pred, 2) for pred in predictions_scaled]

# Output table
output_df = pd.DataFrame({
    'Doctor_Answer': df['Doctor_Answer'],
    'Student_Answer': df['Student_Answer'],
    'Grade (1-10)': [round(g, 2) for g in y],
    'Predicted_Grade (1-10)': predictions_scaled
})

# Show the full table
pd.set_option('display.max_rows', None)
print(output_df)

# Optional: save to file
output_df.to_csv('grades_1_to_10_with_predictions.csv', index=False)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Calculate evaluation metrics
mse = mean_squared_error(y, predictions_scaled)
rmse = np.sqrt(mse)
r2 = r2_score(y, predictions_scaled)

# Print results
print(f"\n Model Evaluation Metrics:")
print(f"Mean Squared Error (MSE): {mse:.3f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.3f}")
print(f"R² Score: {r2:.3f}")